# Generated by Django 4.2.2 on 2025-03-17 17:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0002_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['email'],
                     'permissions': [('can_view_users', 'can view users'), ('can_block_users', 'can block users')],
                     'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
