# Generated by Django 4.2.2 on 2025-03-15 10:51

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(help_text='Email получателя рассылки', max_length=50, unique=True)),
                ('full_name',
                 models.CharField(help_text='Полное имя получателя рассылки', max_length=100, verbose_name='ФИО')),
                ('comment', models.TextField(verbose_name='Введите комментарий о получателе')),
            ],
            options={
                'verbose_name': 'Получатель',
                'verbose_name_plural': 'Получатели',
                'ordering': ['email'],
            },
        ),
    ]
