# Generated by Django 4.2.2 on 2025-03-15 11:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(help_text='Тема сообщения', max_length=50)),
                ('body', models.TextField(verbose_name='Тело сообщения')),
            ],
        ),
    ]
