# Generated by Django 4.2.2 on 2025-03-15 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('mailing', '0002_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_shipment',
                 models.DateTimeField(auto_now_add=True, help_text='Дата и время первой отправки рассылки')),
                ('last_shipment',
                 models.DateTimeField(auto_now_add=True, help_text='Дата и время окончания отправки рассылки')),
                ('status', models.CharField(
                    choices=[('завершена', 'Завершена'), ('создана', 'Создана'), ('запущена', 'Запущена')],
                    default='создана', max_length=20)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.message')),
                ('recipients', models.ManyToManyField(to='mailing.recipient')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
                'ordering': ['message', 'status'],
                'permissions': [('can_unpublish', 'Can unpublish ')],
            },
        ),
    ]
