# Generated by Django 4.2.2 on 2025-03-15 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_mailing'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['subject'], 'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщений'},
        ),
        migrations.AddField(
            model_name='mailing',
            name='is_success',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='message',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mailing.message'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='recipients',
            field=models.ManyToManyField(to='mailing.recipient', verbose_name='Получатели'),
        ),
    ]
