# Generated by Django 4.2.2 on 2025-03-17 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mailing', '0005_mailingattempt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'ordering': ['message', 'status'],
                     'permissions': [('can_view_all_mailings', 'can view all mailings'),
                                     ('can_disable_mailings', 'can disable mailings')], 'verbose_name': 'Рассылка',
                     'verbose_name_plural': 'Рассылки'},
        ),
        migrations.AlterModelOptions(
            name='mailingattempt',
            options={'ordering': ['status'],
                     'permissions': [('can_view_all_mailings_attempts', 'can view all mailings attempts')],
                     'verbose_name': 'Попытка', 'verbose_name_plural': 'Попытки'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['subject'], 'permissions': [('can_view_all_messages', 'can view all messages')],
                     'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщений'},
        ),
        migrations.AlterModelOptions(
            name='recipient',
            options={'ordering': ['email'], 'permissions': [('can_view_all_recipient', 'can view all recipient')],
                     'verbose_name': 'Получатель', 'verbose_name_plural': 'Получатели'},
        ),
        migrations.RenameField(
            model_name='mailing',
            old_name='is_success',
            new_name='is_blocked',
        ),
        migrations.AddField(
            model_name='mailing',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AddField(
            model_name='message',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AddField(
            model_name='recipient',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
    ]
